const Currencies = [
  {
    name: 'Ethereum',
    symbol: 'eth',
    website: '',
    type: 'crypto',
  },
  {
    name: 'adToken',
    symbol: 'adt',
    website: '',
    type: 'crypto',
  },
  {
    name: 'AdEx',
    symbol: 'adx',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Aragon',
    symbol: 'ant',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Australia Dollar',
    symbol: 'aud',
    type: 'fiat',
    symbol: '&#x0024;',
  },
  {
    name: 'Basic Attention Token',
    symbol: 'bat',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Bancor',
    symbol: 'bnt',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Bitcoin',
    symbol: 'btc',
    website: '',
    type: 'crypto',
    symbol: '&#x20BF;',
  },
  {
    name: 'Canada Dollar',
    symbol: 'cad',
    type: 'fiat',
    symbol: '&#x0024;',
  },
  {
    name: 'Cofound.it',
    symbol: 'cfi',
    type: 'crypto',
    url: '',
    trading: false,
  },
  {
    name: 'bitCNY',
    symbol: 'cny',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Creditbit',
    symbol: 'crb',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Civic',
    symbol: 'cvc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Dash',
    symbol: 'dash',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Ethereum Class',
    symbol: 'etc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Euro',
    symbol: 'eur',
    type: 'fiat',
    symbol: '&#x20AC;',
  },
  {
    name: 'United Kingdom Pound',
    symbol: 'gbp',
    type: 'fiat',
    symbol: '&#x20A4;',
  },
  {
    name: 'Gnosis',
    symbol: 'gno',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Golem',
    symbol: 'gnt',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Matchpool',
    symbol: 'gup',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Hong Kong Dollar',
    symbol: 'hkd',
    type: 'fiat',
    symbol: '&#x0024;',
  },
  {
    name: 'Humaniq',
    symbol: 'hmq',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Indonesia Rupiah',
    symbol: 'idr',
    type: 'fiat',
    symbol: 'Rp',
  },
  {
    name: 'Japan Yen',
    symbol: 'jpy',
    type: 'fiat',
    symbol: '&#x00A5;',
  },
  {
    name: 'South Korea Won',
    symbol: 'krw',
    type: 'fiat',
    symbol: '&#x20A9;',
  },
  {
    name: 'Legends Room',
    symbol: 'lgd',
    type: 'crypto',
    url: '',
    trading: false,
  },
  {
    name: 'Lisk',
    symbol: 'lsk',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Litecoin',
    symbol: 'ltc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Lunyr',
    symbol: 'lun',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Monaco',
    symbol: 'mco',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Numeraire',
    symbol: 'nmr',
    type: 'crypto',
    url: '',
  },
  {
    name: 'OmiseGO',
    symbol: 'omg',
    type: 'crypto',
    url: '',
  },
  {
    name: 'TenX',
    symbol: 'pay',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Philippines Peso',
    symbol: 'php',
    type: 'fiat',
    symbol: '&#x20B1;',
  },
  {
    name: 'Patientory',
    symbol: 'ptoy',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Quantum Resistant Ledger',
    symbol: 'qrl',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Qtum',
    symbol: 'qtum',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Augur',
    symbol: 'rep',
    type: 'crypto',
    url: '',
  },
  {
    name: 'iExec',
    symbol: 'rlc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Russia Ruble',
    symbol: 'rub',
    type: 'fiat',
    symbol: '&#x20BD;',
  },
  {
    name: 'Siacoin',
    symbol: 'sgd',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Status',
    symbol: 'snt',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Steem',
    symbol: 'steem',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Storj',
    symbol: 'storj',
    type: 'crypto',
    url: '',
  },
  {
    name: 'WeTrust',
    symbol: 'trst',
    type: 'crypto',
    url: '',
  },
  {
    name: 'UAHPay',
    symbol: 'uah',
    type: 'crypto',
    url: '',
  },
  {
    name: 'United States Dollar',
    symbol: 'usd',
    type: 'fiat',
    symbol: '&#x0024;',
  },
  {
    name: 'Wings',
    symbol: 'wings',
    type: 'crypto',
    url: '',
  },
  {
    name: 'NEM',
    symbol: 'xem',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Stellar Lumens',
    symbol: 'xlm',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Monero',
    symbol: 'xmr',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Ripple',
    symbol: 'xrp',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Zcash',
    symbol: 'zec',
    type: 'crypto',
    url: '',
  },
];

export default Currencies;
