const Currencies = [
  {
    name: 'Ethereum',
    code: 'eth',
    website: '',
    type: 'crypto',
  },
  {
    name: 'adToken',
    code: 'adt',
    website: '',
    type: 'crypto',
  },
  {
    name: 'AdEx',
    code: 'adx',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Aragon',
    code: 'ant',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Australia Dollar',
    code: 'aud',
    type: 'fiat',
    unicodeDecimal: '36',
  },
  {
    name: 'Basic Attention Token',
    code: 'bat',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Bancor',
    code: 'bnt',
    website: '',
    type: 'crypto',
  },
  {
    name: 'Bitcoin',
    code: 'btc',
    website: '',
    type: 'crypto',
    unicodeDecimal: '8383',
  },
  {
    name: 'Canada Dollar',
    code: 'cad',
    type: 'fiat',
    unicodeDecimal: '36',
  },
  {
    name: 'Cofound.it',
    code: 'cfi',
    type: 'crypto',
    url: '',
    trading: false,
  },
  {
    name: 'bitCNY',
    code: 'cny',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Creditbit',
    code: 'crb',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Civic',
    code: 'cvc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Dash',
    code: 'dash',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Ethereum Class',
    code: 'etc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Euro',
    code: 'eur',
    type: 'fiat',
    unicodeDecimal: '8364',
  },
  {
    name: 'United Kingdom Pound',
    code: 'gbp',
    type: 'fiat',
    unicodeDecimal: '8356',
  },
  {
    name: 'Gnosis',
    code: 'gno',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Golem',
    code: 'gnt',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Matchpool',
    code: 'gup',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Hong Kong Dollar',
    code: 'hkd',
    type: 'fiat',
    unicodeDecimal: '36',
  },
  {
    name: 'Humaniq',
    code: 'hmq',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Indonesia Rupiah',
    code: 'idr',
    type: 'fiat',
    symbol: 'Rp',
  },
  {
    name: 'Japan Yen',
    code: 'jpy',
    type: 'fiat',
    unicodeDecimal: '165',
  },
  {
    name: 'South Korea Won',
    code: 'krw',
    type: 'fiat',
    unicodeDecimal: '8361',
  },
  {
    name: 'Legends Room',
    code: 'lgd',
    type: 'crypto',
    url: '',
    trading: false,
  },
  {
    name: 'Lisk',
    code: 'lsk',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Litecoin',
    code: 'ltc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Lunyr',
    code: 'lun',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Monaco',
    code: 'mco',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Numeraire',
    code: 'nmr',
    type: 'crypto',
    url: '',
  },
  {
    name: 'OmiseGO',
    code: 'omg',
    type: 'crypto',
    url: '',
  },
  {
    name: 'TenX',
    code: 'pay',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Philippines Peso',
    code: 'php',
    type: 'fiat',
    unicodeDecimal: '8369',
  },
  {
    name: 'Patientory',
    code: 'ptoy',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Quantum Resistant Ledger',
    code: 'qrl',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Qtum',
    code: 'qtum',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Augur',
    code: 'rep',
    type: 'crypto',
    url: '',
  },
  {
    name: 'iExec',
    code: 'rlc',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Russia Ruble',
    code: 'rub',
    type: 'fiat',
    unicodeDecimal: '8381',
  },
  {
    name: 'Siacoin',
    code: 'sgd',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Status',
    code: 'snt',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Steem',
    code: 'steem',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Storj',
    code: 'storj',
    type: 'crypto',
    url: '',
  },
  {
    name: 'WeTrust',
    code: 'trst',
    type: 'crypto',
    url: '',
  },
  {
    name: 'UAHPay',
    code: 'uah',
    type: 'crypto',
    url: '',
  },
  {
    name: 'United States Dollar',
    code: 'usd',
    type: 'fiat',
    unicodeDecimal: '36',
  },
  {
    name: 'Wings',
    code: 'wings',
    type: 'crypto',
    url: '',
  },
  {
    name: 'NEM',
    code: 'xem',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Stellar Lumens',
    code: 'xlm',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Monero',
    code: 'xmr',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Ripple',
    code: 'xrp',
    type: 'crypto',
    url: '',
  },
  {
    name: 'Zcash',
    code: 'zec',
    type: 'crypto',
    url: '',
  },
];

export default Currencies;
